"""empty message

Revision ID: fe3e913f56d6
Revises: 0f7c4e672904
Create Date: 2020-02-14 16:19:42.263303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3e913f56d6'
down_revision = '0f7c4e672904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('gender', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'gender')
    # ### end Alembic commands ###
